# Generated by Django 6.0.6 on 2026-07-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='upadted_at',
            new_name='updated_at',
        ),
    ]
