# Generated by Django 6.0.6 on 2026-07-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_sociallinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'SocialLinks'},
        ),
    ]
