# Generated by Django 6.0.6 on 2026-07-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_sociallinks_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallinks',
            old_name='paltform',
            new_name='platform',
        ),
    ]
