# Generated by Django 6.0.6 on 2026-07-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_rename_paltform_sociallinks_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='link',
            field=models.URLField(max_length=150),
        ),
    ]
